'use no memo';

// src/constants/bloodValues.ts

export type Gender = 'male' | 'female' | 'diverse'

export interface BloodValue {
  id: string
  name: string
  shortName?: string
  category: string
  gender: 'all' | 'female' | 'male' // wer sieht diesen Wert
  cycleDependent?: boolean           // variiert je nach Zyklusphase
  units: string[]                    // mögliche Einheiten
  defaultUnit: string
  referenceRanges?: {
    male?: { min: number; max: number }
    female?: { min: number; max: number }
    all?: { min: number; max: number }
  }
  note?: string                      // Hinweis für den User
}

export const BLOOD_VALUE_CATEGORIES = [
  '🩸 Blutbild',
  '🍬 Stoffwechsel',
  '🫀 Herz & Gefäße',
  '🫁 Niere & Elektrolyte',
  '🟤 Leber & Galle',
  '🦋 Schilddrüse',
  '💊 Vitamine & Mineralstoffe',
  '⚡ Entzündung & Immunsystem',
  '🧬 Hormone (allgemein)',
  '♀️ Hormone (weiblich)',
  '♂️ Hormone (männlich)',
  '🩺 Sonstiges',
]

export const BLOOD_VALUES: BloodValue[] = [
  // ─── 🩸 BLUTBILD ───────────────────────────────────────────────
  {
    id: 'hemoglobin',
    name: 'Hämoglobin',
    shortName: 'Hb',
    category: '🩸 Blutbild',
    gender: 'all',
    units: ['g/dL', 'g/L', 'mmol/L'],
    defaultUnit: 'g/dL',
    referenceRanges: {
      male: { min: 13.5, max: 17.5 },
      female: { min: 12.0, max: 16.0 },
    },
  },
  {
    id: 'hematocrit',
    name: 'Hämatokrit',
    shortName: 'Hkt',
    category: '🩸 Blutbild',
    gender: 'all',
    units: ['%', 'L/L'],
    defaultUnit: '%',
    referenceRanges: {
      male: { min: 40, max: 52 },
      female: { min: 36, max: 48 },
    },
  },
  {
    id: 'erythrocytes',
    name: 'Erythrozyten',
    shortName: 'RBC',
    category: '🩸 Blutbild',
    gender: 'all',
    units: ['Mio/µL', '10¹²/L'],
    defaultUnit: 'Mio/µL',
    referenceRanges: {
      male: { min: 4.4, max: 5.9 },
      female: { min: 3.8, max: 5.2 },
    },
  },
  {
    id: 'leukocytes',
    name: 'Leukozyten',
    shortName: 'WBC',
    category: '🩸 Blutbild',
    gender: 'all',
    units: ['Tsd/µL', '10⁹/L', '/µL'],
    defaultUnit: 'Tsd/µL',
    referenceRanges: { all: { min: 4.0, max: 10.0 } },
  },
  {
    id: 'thrombocytes',
    name: 'Thrombozyten',
    shortName: 'PLT',
    category: '🩸 Blutbild',
    gender: 'all',
    units: ['Tsd/µL', '10⁹/L'],
    defaultUnit: 'Tsd/µL',
    referenceRanges: { all: { min: 150, max: 400 } },
  },
  {
    id: 'mcv',
    name: 'MCV (mittl. Erythrozytenvolumen)',
    shortName: 'MCV',
    category: '🩸 Blutbild',
    gender: 'all',
    units: ['fL'],
    defaultUnit: 'fL',
    referenceRanges: { all: { min: 80, max: 100 } },
  },
  {
    id: 'mch',
    name: 'MCH (mittl. Hb-Gehalt)',
    shortName: 'MCH',
    category: '🩸 Blutbild',
    gender: 'all',
    units: ['pg'],
    defaultUnit: 'pg',
    referenceRanges: { all: { min: 27, max: 34 } },
  },
  {
    id: 'mchc',
    name: 'MCHC (mittl. Hb-Konzentration)',
    shortName: 'MCHC',
    category: '🩸 Blutbild',
    gender: 'all',
    units: ['g/dL', 'g/L'],
    defaultUnit: 'g/dL',
    referenceRanges: { all: { min: 32, max: 36 } },
  },
  {
    id: 'rdw',
    name: 'RDW (Erythrozytenverteilungsbreite)',
    shortName: 'RDW',
    category: '🩸 Blutbild',
    gender: 'all',
    units: ['%'],
    defaultUnit: '%',
    referenceRanges: { all: { min: 11.5, max: 14.5 } },
  },
  {
    id: 'neutrophils',
    name: 'Neutrophile',
    category: '🩸 Blutbild',
    gender: 'all',
    units: ['%', 'Tsd/µL'],
    defaultUnit: '%',
    referenceRanges: { all: { min: 50, max: 75 } },
  },
  {
    id: 'lymphocytes',
    name: 'Lymphozyten',
    category: '🩸 Blutbild',
    gender: 'all',
    units: ['%', 'Tsd/µL'],
    defaultUnit: '%',
    referenceRanges: { all: { min: 20, max: 45 } },
  },
  {
    id: 'monocytes',
    name: 'Monozyten',
    category: '🩸 Blutbild',
    gender: 'all',
    units: ['%', 'Tsd/µL'],
    defaultUnit: '%',
    referenceRanges: { all: { min: 2, max: 10 } },
  },
  {
    id: 'eosinophils',
    name: 'Eosinophile',
    category: '🩸 Blutbild',
    gender: 'all',
    units: ['%', 'Tsd/µL'],
    defaultUnit: '%',
    referenceRanges: { all: { min: 1, max: 6 } },
  },
  {
    id: 'basophils',
    name: 'Basophile',
    category: '🩸 Blutbild',
    gender: 'all',
    units: ['%', 'Tsd/µL'],
    defaultUnit: '%',
    referenceRanges: { all: { min: 0, max: 1 } },
  },

  // ─── 🍬 STOFFWECHSEL ───────────────────────────────────────────
  {
    id: 'glucose',
    name: 'Glukose (Blutzucker)',
    shortName: 'BZ',
    category: '🍬 Stoffwechsel',
    gender: 'all',
    units: ['mg/dL', 'mmol/L'],
    defaultUnit: 'mg/dL',
    referenceRanges: { all: { min: 70, max: 100 } },
    note: 'Nüchternwert',
  },
  {
    id: 'hba1c',
    name: 'HbA1c (Langzeitblutzucker)',
    shortName: 'HbA1c',
    category: '🍬 Stoffwechsel',
    gender: 'all',
    units: ['%', 'mmol/mol'],
    defaultUnit: '%',
    referenceRanges: { all: { min: 4.0, max: 5.7 } },
  },
  {
    id: 'cholesterol',
    name: 'Gesamtcholesterin',
    category: '🍬 Stoffwechsel',
    gender: 'all',
    units: ['mg/dL', 'mmol/L'],
    defaultUnit: 'mg/dL',
    referenceRanges: { all: { min: 0, max: 200 } },
  },
  {
    id: 'ldl',
    name: 'LDL-Cholesterin',
    shortName: 'LDL',
    category: '🍬 Stoffwechsel',
    gender: 'all',
    units: ['mg/dL', 'mmol/L'],
    defaultUnit: 'mg/dL',
    referenceRanges: { all: { min: 0, max: 130 } },
  },
  {
    id: 'hdl',
    name: 'HDL-Cholesterin',
    shortName: 'HDL',
    category: '🍬 Stoffwechsel',
    gender: 'all',
    units: ['mg/dL', 'mmol/L'],
    defaultUnit: 'mg/dL',
    referenceRanges: {
      male: { min: 40, max: 60 },
      female: { min: 50, max: 80 },
    },
  },
  {
    id: 'triglycerides',
    name: 'Triglyzeride',
    category: '🍬 Stoffwechsel',
    gender: 'all',
    units: ['mg/dL', 'mmol/L'],
    defaultUnit: 'mg/dL',
    referenceRanges: { all: { min: 0, max: 150 } },
  },
  {
    id: 'insulin',
    name: 'Insulin (Nüchtern)',
    category: '🍬 Stoffwechsel',
    gender: 'all',
    units: ['µIU/mL', 'pmol/L'],
    defaultUnit: 'µIU/mL',
    referenceRanges: { all: { min: 2, max: 25 } },
  },
  {
    id: 'uric_acid',
    name: 'Harnsäure',
    category: '🍬 Stoffwechsel',
    gender: 'all',
    units: ['mg/dL', 'µmol/L'],
    defaultUnit: 'mg/dL',
    referenceRanges: {
      male: { min: 3.4, max: 7.0 },
      female: { min: 2.4, max: 5.7 },
    },
  },

  // ─── 🫀 HERZ & GEFÄSSE ─────────────────────────────────────────
  {
    id: 'crp',
    name: 'CRP (C-reaktives Protein)',
    shortName: 'CRP',
    category: '🫀 Herz & Gefäße',
    gender: 'all',
    units: ['mg/L', 'mg/dL'],
    defaultUnit: 'mg/L',
    referenceRanges: { all: { min: 0, max: 5 } },
  },
  {
    id: 'hs_crp',
    name: 'hsCRP (hochsensitiv)',
    shortName: 'hsCRP',
    category: '🫀 Herz & Gefäße',
    gender: 'all',
    units: ['mg/L'],
    defaultUnit: 'mg/L',
    referenceRanges: { all: { min: 0, max: 3 } },
  },
  {
    id: 'troponin',
    name: 'Troponin T/I',
    category: '🫀 Herz & Gefäße',
    gender: 'all',
    units: ['ng/L', 'pg/mL'],
    defaultUnit: 'ng/L',
  },
  {
    id: 'bnp',
    name: 'BNP / NT-proBNP',
    category: '🫀 Herz & Gefäße',
    gender: 'all',
    units: ['pg/mL', 'ng/L'],
    defaultUnit: 'pg/mL',
  },
  {
    id: 'homocysteine',
    name: 'Homocystein',
    category: '🫀 Herz & Gefäße',
    gender: 'all',
    units: ['µmol/L'],
    defaultUnit: 'µmol/L',
    referenceRanges: { all: { min: 5, max: 15 } },
  },

  // ─── 🫁 NIERE & ELEKTROLYTE ────────────────────────────────────
  {
    id: 'creatinine',
    name: 'Kreatinin',
    category: '🫁 Niere & Elektrolyte',
    gender: 'all',
    units: ['mg/dL', 'µmol/L'],
    defaultUnit: 'mg/dL',
    referenceRanges: {
      male: { min: 0.7, max: 1.2 },
      female: { min: 0.5, max: 1.0 },
    },
  },
  {
    id: 'gfr',
    name: 'GFR (Nierenfiltration)',
    shortName: 'eGFR',
    category: '🫁 Niere & Elektrolyte',
    gender: 'all',
    units: ['mL/min/1,73m²'],
    defaultUnit: 'mL/min/1,73m²',
    referenceRanges: { all: { min: 60, max: 120 } },
  },
  {
    id: 'urea',
    name: 'Harnstoff',
    category: '🫁 Niere & Elektrolyte',
    gender: 'all',
    units: ['mg/dL', 'mmol/L'],
    defaultUnit: 'mg/dL',
    referenceRanges: { all: { min: 15, max: 45 } },
  },
  {
    id: 'sodium',
    name: 'Natrium',
    shortName: 'Na⁺',
    category: '🫁 Niere & Elektrolyte',
    gender: 'all',
    units: ['mmol/L', 'mEq/L'],
    defaultUnit: 'mmol/L',
    referenceRanges: { all: { min: 135, max: 145 } },
  },
  {
    id: 'potassium',
    name: 'Kalium',
    shortName: 'K⁺',
    category: '🫁 Niere & Elektrolyte',
    gender: 'all',
    units: ['mmol/L', 'mEq/L'],
    defaultUnit: 'mmol/L',
    referenceRanges: { all: { min: 3.5, max: 5.0 } },
  },
  {
    id: 'calcium',
    name: 'Kalzium',
    shortName: 'Ca²⁺',
    category: '🫁 Niere & Elektrolyte',
    gender: 'all',
    units: ['mmol/L', 'mg/dL', 'mEq/L'],
    defaultUnit: 'mmol/L',
    referenceRanges: { all: { min: 2.15, max: 2.55 } },
  },
  {
    id: 'magnesium',
    name: 'Magnesium',
    shortName: 'Mg²⁺',
    category: '🫁 Niere & Elektrolyte',
    gender: 'all',
    units: ['mmol/L', 'mg/dL', 'mEq/L'],
    defaultUnit: 'mmol/L',
    referenceRanges: { all: { min: 0.7, max: 1.05 } },
  },
  {
    id: 'phosphate',
    name: 'Phosphat',
    category: '🫁 Niere & Elektrolyte',
    gender: 'all',
    units: ['mmol/L', 'mg/dL'],
    defaultUnit: 'mmol/L',
    referenceRanges: { all: { min: 0.87, max: 1.45 } },
  },
  {
    id: 'chloride',
    name: 'Chlorid',
    shortName: 'Cl⁻',
    category: '🫁 Niere & Elektrolyte',
    gender: 'all',
    units: ['mmol/L', 'mEq/L'],
    defaultUnit: 'mmol/L',
    referenceRanges: { all: { min: 98, max: 107 } },
  },

  // ─── 🟤 LEBER & GALLE ─────────────────────────────────────────
  {
    id: 'got',
    name: 'GOT / AST',
    shortName: 'GOT',
    category: '🟤 Leber & Galle',
    gender: 'all',
    units: ['U/L', 'µkat/L'],
    defaultUnit: 'U/L',
    referenceRanges: {
      male: { min: 0, max: 50 },
      female: { min: 0, max: 35 },
    },
  },
  {
    id: 'gpt',
    name: 'GPT / ALT',
    shortName: 'GPT',
    category: '🟤 Leber & Galle',
    gender: 'all',
    units: ['U/L', 'µkat/L'],
    defaultUnit: 'U/L',
    referenceRanges: {
      male: { min: 0, max: 50 },
      female: { min: 0, max: 35 },
    },
  },
  {
    id: 'ggt',
    name: 'GGT (Gamma-GT)',
    shortName: 'GGT',
    category: '🟤 Leber & Galle',
    gender: 'all',
    units: ['U/L', 'µkat/L'],
    defaultUnit: 'U/L',
    referenceRanges: {
      male: { min: 0, max: 60 },
      female: { min: 0, max: 40 },
    },
  },
  {
    id: 'ap',
    name: 'Alkalische Phosphatase',
    shortName: 'AP',
    category: '🟤 Leber & Galle',
    gender: 'all',
    units: ['U/L'],
    defaultUnit: 'U/L',
    referenceRanges: { all: { min: 40, max: 130 } },
  },
  {
    id: 'bilirubin_total',
    name: 'Bilirubin (gesamt)',
    category: '🟤 Leber & Galle',
    gender: 'all',
    units: ['mg/dL', 'µmol/L'],
    defaultUnit: 'mg/dL',
    referenceRanges: { all: { min: 0.1, max: 1.2 } },
  },
  {
    id: 'bilirubin_direct',
    name: 'Bilirubin (direkt)',
    category: '🟤 Leber & Galle',
    gender: 'all',
    units: ['mg/dL', 'µmol/L'],
    defaultUnit: 'mg/dL',
    referenceRanges: { all: { min: 0, max: 0.3 } },
  },
  {
    id: 'albumin',
    name: 'Albumin',
    category: '🟤 Leber & Galle',
    gender: 'all',
    units: ['g/dL', 'g/L'],
    defaultUnit: 'g/dL',
    referenceRanges: { all: { min: 3.5, max: 5.5 } },
  },
  {
    id: 'total_protein',
    name: 'Gesamtprotein',
    category: '🟤 Leber & Galle',
    gender: 'all',
    units: ['g/dL', 'g/L'],
    defaultUnit: 'g/dL',
    referenceRanges: { all: { min: 6.0, max: 8.3 } },
  },

  // ─── 🦋 SCHILDDRÜSE ────────────────────────────────────────────
  {
    id: 'tsh',
    name: 'TSH',
    category: '🦋 Schilddrüse',
    gender: 'all',
    units: ['mIU/L', 'µIU/mL'],
    defaultUnit: 'mIU/L',
    referenceRanges: { all: { min: 0.4, max: 4.0 } },
  },
  {
    id: 'ft3',
    name: 'Freies T3 (fT3)',
    shortName: 'fT3',
    category: '🦋 Schilddrüse',
    gender: 'all',
    units: ['pmol/L', 'pg/mL', 'ng/dL'],
    defaultUnit: 'pmol/L',
    referenceRanges: { all: { min: 3.1, max: 6.8 } },
  },
  {
    id: 'ft4',
    name: 'Freies T4 (fT4)',
    shortName: 'fT4',
    category: '🦋 Schilddrüse',
    gender: 'all',
    units: ['pmol/L', 'ng/dL'],
    defaultUnit: 'pmol/L',
    referenceRanges: { all: { min: 12, max: 22 } },
  },
  {
    id: 'tpo_ak',
    name: 'TPO-Antikörper',
    shortName: 'TPO-AK',
    category: '🦋 Schilddrüse',
    gender: 'all',
    units: ['IU/mL', 'U/mL'],
    defaultUnit: 'IU/mL',
    referenceRanges: { all: { min: 0, max: 35 } },
  },

  // ─── 💊 VITAMINE & MINERALSTOFFE ───────────────────────────────
  {
    id: 'vitamin_d',
    name: 'Vitamin D (25-OH)',
    shortName: 'Vit. D',
    category: '💊 Vitamine & Mineralstoffe',
    gender: 'all',
    units: ['ng/mL', 'nmol/L'],
    defaultUnit: 'ng/mL',
    referenceRanges: { all: { min: 30, max: 100 } },
  },
  {
    id: 'vitamin_b12',
    name: 'Vitamin B12',
    shortName: 'Vit. B12',
    category: '💊 Vitamine & Mineralstoffe',
    gender: 'all',
    units: ['pg/mL', 'pmol/L'],
    defaultUnit: 'pg/mL',
    referenceRanges: { all: { min: 200, max: 900 } },
  },
  {
    id: 'folate',
    name: 'Folsäure',
    category: '💊 Vitamine & Mineralstoffe',
    gender: 'all',
    units: ['ng/mL', 'nmol/L'],
    defaultUnit: 'ng/mL',
    referenceRanges: { all: { min: 3, max: 20 } },
  },
  {
    id: 'ferritin',
    name: 'Ferritin',
    category: '💊 Vitamine & Mineralstoffe',
    gender: 'all',
    units: ['ng/mL', 'µg/L'],
    defaultUnit: 'ng/mL',
    referenceRanges: {
      male: { min: 30, max: 400 },
      female: { min: 15, max: 150 },
    },
    note: 'Referenzwerte je nach Labor unterschiedlich',
  },
  {
    id: 'iron',
    name: 'Eisen (Serum)',
    category: '💊 Vitamine & Mineralstoffe',
    gender: 'all',
    units: ['µg/dL', 'µmol/L'],
    defaultUnit: 'µg/dL',
    referenceRanges: {
      male: { min: 65, max: 175 },
      female: { min: 50, max: 170 },
    },
  },
  {
    id: 'transferrin',
    name: 'Transferrin',
    category: '💊 Vitamine & Mineralstoffe',
    gender: 'all',
    units: ['g/L', 'mg/dL'],
    defaultUnit: 'g/L',
    referenceRanges: { all: { min: 2.0, max: 3.6 } },
  },
  {
    id: 'tibc',
    name: 'TIBC (Eisenbindungskapazität)',
    shortName: 'TIBC',
    category: '💊 Vitamine & Mineralstoffe',
    gender: 'all',
    units: ['µg/dL', 'µmol/L'],
    defaultUnit: 'µg/dL',
    referenceRanges: { all: { min: 250, max: 450 } },
  },
  {
    id: 'zinc',
    name: 'Zink',
    category: '💊 Vitamine & Mineralstoffe',
    gender: 'all',
    units: ['µg/dL', 'µmol/L'],
    defaultUnit: 'µg/dL',
    referenceRanges: { all: { min: 70, max: 120 } },
  },
  {
    id: 'selenium',
    name: 'Selen',
    category: '💊 Vitamine & Mineralstoffe',
    gender: 'all',
    units: ['µg/L', 'nmol/L'],
    defaultUnit: 'µg/L',
    referenceRanges: { all: { min: 60, max: 120 } },
  },
  {
    id: 'vitamin_a',
    name: 'Vitamin A (Retinol)',
    shortName: 'Vit. A',
    category: '💊 Vitamine & Mineralstoffe',
    gender: 'all',
    units: ['µg/dL', 'µmol/L'],
    defaultUnit: 'µg/dL',
  },
  {
    id: 'vitamin_e',
    name: 'Vitamin E (Tocopherol)',
    shortName: 'Vit. E',
    category: '💊 Vitamine & Mineralstoffe',
    gender: 'all',
    units: ['mg/L', 'µmol/L'],
    defaultUnit: 'mg/L',
  },

  // ─── ⚡ ENTZÜNDUNG & IMMUNSYSTEM ───────────────────────────────
  {
    id: 'esr',
    name: 'BSG (Blutsenkungsgeschwindigkeit)',
    shortName: 'BSG',
    category: '⚡ Entzündung & Immunsystem',
    gender: 'all',
    units: ['mm/h'],
    defaultUnit: 'mm/h',
    referenceRanges: {
      male: { min: 0, max: 15 },
      female: { min: 0, max: 20 },
    },
  },
  {
    id: 'pct',
    name: 'Procalcitonin',
    shortName: 'PCT',
    category: '⚡ Entzündung & Immunsystem',
    gender: 'all',
    units: ['ng/mL', 'µg/L'],
    defaultUnit: 'ng/mL',
    referenceRanges: { all: { min: 0, max: 0.5 } },
  },
  {
    id: 'il6',
    name: 'Interleukin-6',
    shortName: 'IL-6',
    category: '⚡ Entzündung & Immunsystem',
    gender: 'all',
    units: ['pg/mL'],
    defaultUnit: 'pg/mL',
    referenceRanges: { all: { min: 0, max: 7 } },
  },
  {
    id: 'iga',
    name: 'Immunglobulin A (IgA)',
    shortName: 'IgA',
    category: '⚡ Entzündung & Immunsystem',
    gender: 'all',
    units: ['g/L', 'mg/dL'],
    defaultUnit: 'g/L',
    referenceRanges: { all: { min: 0.7, max: 4.0 } },
  },
  {
    id: 'igg',
    name: 'Immunglobulin G (IgG)',
    shortName: 'IgG',
    category: '⚡ Entzündung & Immunsystem',
    gender: 'all',
    units: ['g/L', 'mg/dL'],
    defaultUnit: 'g/L',
    referenceRanges: { all: { min: 7.0, max: 16.0 } },
  },
  {
    id: 'igm',
    name: 'Immunglobulin M (IgM)',
    shortName: 'IgM',
    category: '⚡ Entzündung & Immunsystem',
    gender: 'all',
    units: ['g/L', 'mg/dL'],
    defaultUnit: 'g/L',
    referenceRanges: { all: { min: 0.4, max: 2.3 } },
  },

  // ─── 🧬 HORMONE (ALLGEMEIN) ────────────────────────────────────
  {
    id: 'cortisol',
    name: 'Cortisol',
    category: '🧬 Hormone (allgemein)',
    gender: 'all',
    units: ['µg/dL', 'nmol/L'],
    defaultUnit: 'µg/dL',
    referenceRanges: { all: { min: 6, max: 23 } },
    note: 'Morgenblut (8 Uhr)',
  },
  {
    id: 'dhea_s',
    name: 'DHEA-S',
    category: '🧬 Hormone (allgemein)',
    gender: 'all',
    units: ['µg/dL', 'µmol/L'],
    defaultUnit: 'µg/dL',
    referenceRanges: {
      male: { min: 80, max: 560 },
      female: { min: 35, max: 430 },
    },
  },
  {
    id: 'insulin_like_growth_factor',
    name: 'IGF-1 (Wachstumshormon)',
    shortName: 'IGF-1',
    category: '🧬 Hormone (allgemein)',
    gender: 'all',
    units: ['ng/mL', 'nmol/L'],
    defaultUnit: 'ng/mL',
  },
  {
    id: 'growth_hormone',
    name: 'Wachstumshormon (GH/HGH)',
    shortName: 'GH',
    category: '🧬 Hormone (allgemein)',
    gender: 'all',
    units: ['ng/mL', 'µg/L', 'mIU/L'],
    defaultUnit: 'ng/mL',
  },
  {
    id: 'prolactin',
    name: 'Prolaktin',
    category: '🧬 Hormone (allgemein)',
    gender: 'all',
    units: ['ng/mL', 'mIU/L', 'µg/L'],
    defaultUnit: 'ng/mL',
    referenceRanges: {
      male: { min: 2, max: 18 },
      female: { min: 2, max: 29 },
    },
    cycleDependent: true,
  },
  {
    id: 'insulin_fasting',
    name: 'Nüchterninsulin',
    category: '🧬 Hormone (allgemein)',
    gender: 'all',
    units: ['µIU/mL', 'pmol/L'],
    defaultUnit: 'µIU/mL',
    referenceRanges: { all: { min: 2, max: 25 } },
  },

  // ─── ♀️ HORMONE (WEIBLICH) ─────────────────────────────────────
  {
    id: 'estradiol',
    name: 'Östradiol (E2)',
    shortName: 'E2',
    category: '♀️ Hormone (weiblich)',
    gender: 'female',
    cycleDependent: true,
    units: ['pg/mL', 'pmol/L'],
    defaultUnit: 'pg/mL',
    note: 'Stark zyklusabhängig – Zyklusphase angeben!',
  },
  {
    id: 'estrone',
    name: 'Östron (E1)',
    shortName: 'E1',
    category: '♀️ Hormone (weiblich)',
    gender: 'female',
    cycleDependent: true,
    units: ['pg/mL', 'pmol/L'],
    defaultUnit: 'pg/mL',
  },
  {
    id: 'estriol',
    name: 'Östriol (E3)',
    shortName: 'E3',
    category: '♀️ Hormone (weiblich)',
    gender: 'female',
    units: ['ng/mL', 'nmol/L'],
    defaultUnit: 'ng/mL',
    note: 'Relevant in der Schwangerschaft',
  },
  {
    id: 'progesterone',
    name: 'Progesteron',
    category: '♀️ Hormone (weiblich)',
    gender: 'female',
    cycleDependent: true,
    units: ['ng/mL', 'nmol/L'],
    defaultUnit: 'ng/mL',
    note: 'Stark zyklusabhängig – Zyklusphase angeben!',
  },
  {
    id: 'lh',
    name: 'LH (Luteinisierendes Hormon)',
    shortName: 'LH',
    category: '♀️ Hormone (weiblich)',
    gender: 'female',
    cycleDependent: true,
    units: ['IU/L', 'mIU/mL'],
    defaultUnit: 'IU/L',
    note: 'Stark zyklusabhängig',
  },
  {
    id: 'fsh',
    name: 'FSH (Follikelstimulierendes Hormon)',
    shortName: 'FSH',
    category: '♀️ Hormone (weiblich)',
    gender: 'female',
    cycleDependent: true,
    units: ['IU/L', 'mIU/mL'],
    defaultUnit: 'IU/L',
    note: 'Stark zyklusabhängig',
  },
  {
    id: 'amh',
    name: 'AMH (Anti-Müller-Hormon)',
    shortName: 'AMH',
    category: '♀️ Hormone (weiblich)',
    gender: 'female',
    units: ['ng/mL', 'pmol/L'],
    defaultUnit: 'ng/mL',
    note: 'Maß für die ovarielle Reserve',
  },
  {
    id: 'shbg_female',
    name: 'SHBG',
    category: '♀️ Hormone (weiblich)',
    gender: 'female',
    units: ['nmol/L'],
    defaultUnit: 'nmol/L',
    referenceRanges: { female: { min: 18, max: 114 } },
  },
  {
    id: 'free_testosterone_female',
    name: 'Freies Testosteron (Frau)',
    category: '♀️ Hormone (weiblich)',
    gender: 'female',
    units: ['pg/mL', 'pmol/L'],
    defaultUnit: 'pg/mL',
    referenceRanges: { female: { min: 0.3, max: 5.0 } },
  },
  {
    id: 'total_testosterone_female',
    name: 'Gesamttestosteron (Frau)',
    category: '♀️ Hormone (weiblich)',
    gender: 'female',
    units: ['ng/dL', 'nmol/L'],
    defaultUnit: 'ng/dL',
    referenceRanges: { female: { min: 15, max: 70 } },
  },
  {
    id: 'dhea_female',
    name: 'DHEA (Frau)',
    category: '♀️ Hormone (weiblich)',
    gender: 'female',
    units: ['ng/mL', 'nmol/L'],
    defaultUnit: 'ng/mL',
    cycleDependent: true,
  },
  {
    id: 'hcg',
    name: 'Beta-HCG (Schwangerschaft)',
    shortName: 'β-HCG',
    category: '♀️ Hormone (weiblich)',
    gender: 'female',
    units: ['mIU/mL', 'IU/L'],
    defaultUnit: 'mIU/mL',
  },

  // ─── ♂️ HORMONE (MÄNNLICH) ─────────────────────────────────────
  {
    id: 'total_testosterone_male',
    name: 'Gesamttestosteron (Mann)',
    shortName: 'Testosteron',
    category: '♂️ Hormone (männlich)',
    gender: 'male',
    units: ['ng/dL', 'nmol/L'],
    defaultUnit: 'ng/dL',
    referenceRanges: { male: { min: 300, max: 1000 } },
  },
  {
    id: 'free_testosterone_male',
    name: 'Freies Testosteron (Mann)',
    category: '♂️ Hormone (männlich)',
    gender: 'male',
    units: ['pg/mL', 'pmol/L'],
    defaultUnit: 'pg/mL',
    referenceRanges: { male: { min: 50, max: 210 } },
  },
  {
    id: 'shbg_male',
    name: 'SHBG (Mann)',
    shortName: 'SHBG',
    category: '♂️ Hormone (männlich)',
    gender: 'male',
    units: ['nmol/L'],
    defaultUnit: 'nmol/L',
    referenceRanges: { male: { min: 10, max: 57 } },
  },
  {
    id: 'dht',
    name: 'DHT (Dihydrotestosteron)',
    shortName: 'DHT',
    category: '♂️ Hormone (männlich)',
    gender: 'male',
    units: ['ng/dL', 'nmol/L'],
    defaultUnit: 'ng/dL',
    referenceRanges: { male: { min: 30, max: 85 } },
  },
  {
    id: 'lh_male',
    name: 'LH (Mann)',
    shortName: 'LH',
    category: '♂️ Hormone (männlich)',
    gender: 'male',
    units: ['IU/L', 'mIU/mL'],
    defaultUnit: 'IU/L',
    referenceRanges: { male: { min: 1.7, max: 8.6 } },
  },
  {
    id: 'fsh_male',
    name: 'FSH (Mann)',
    shortName: 'FSH',
    category: '♂️ Hormone (männlich)',
    gender: 'male',
    units: ['IU/L', 'mIU/mL'],
    defaultUnit: 'IU/L',
    referenceRanges: { male: { min: 1.5, max: 12.4 } },
  },
  {
    id: 'estradiol_male',
    name: 'Östradiol (Mann)',
    shortName: 'E2',
    category: '♂️ Hormone (männlich)',
    gender: 'male',
    units: ['pg/mL', 'pmol/L'],
    defaultUnit: 'pg/mL',
    referenceRanges: { male: { min: 10, max: 40 } },
  },
  {
    id: 'psa',
    name: 'PSA (Prostata)',
    shortName: 'PSA',
    category: '♂️ Hormone (männlich)',
    gender: 'male',
    units: ['ng/mL'],
    defaultUnit: 'ng/mL',
    referenceRanges: { male: { min: 0, max: 4 } },
    note: 'Referenzwert altersabhängig',
  },

  // ─── 🩺 SONSTIGES ──────────────────────────────────────────────
  {
    id: 'inr',
    name: 'INR (Gerinnungszeit)',
    shortName: 'INR',
    category: '🩺 Sonstiges',
    gender: 'all',
    units: [''],
    defaultUnit: '',
    referenceRanges: { all: { min: 0.85, max: 1.15 } },
  },
  {
    id: 'ptt',
    name: 'PTT / aPTT (Gerinnungszeit)',
    shortName: 'aPTT',
    category: '🩺 Sonstiges',
    gender: 'all',
    units: ['Sekunden'],
    defaultUnit: 'Sekunden',
    referenceRanges: { all: { min: 25, max: 38 } },
  },
  {
    id: 'fibrinogen',
    name: 'Fibrinogen',
    category: '🩺 Sonstiges',
    gender: 'all',
    units: ['g/L', 'mg/dL'],
    defaultUnit: 'g/L',
    referenceRanges: { all: { min: 2.0, max: 4.0 } },
  },
  {
    id: 'dimer',
    name: 'D-Dimer',
    category: '🩺 Sonstiges',
    gender: 'all',
    units: ['µg/mL', 'mg/L', 'ng/mL'],
    defaultUnit: 'µg/mL',
    referenceRanges: { all: { min: 0, max: 0.5 } },
  },
  {
    id: 'amylase',
    name: 'Amylase',
    category: '🩺 Sonstiges',
    gender: 'all',
    units: ['U/L'],
    defaultUnit: 'U/L',
    referenceRanges: { all: { min: 28, max: 100 } },
  },
  {
    id: 'lipase',
    name: 'Lipase',
    category: '🩺 Sonstiges',
    gender: 'all',
    units: ['U/L'],
    defaultUnit: 'U/L',
    referenceRanges: { all: { min: 13, max: 60 } },
  },
  {
    id: 'ldh',
    name: 'LDH (Laktatdehydrogenase)',
    shortName: 'LDH',
    category: '🩺 Sonstiges',
    gender: 'all',
    units: ['U/L', 'µkat/L'],
    defaultUnit: 'U/L',
    referenceRanges: {
      male: { min: 135, max: 225 },
      female: { min: 135, max: 214 },
    },
  },
]

// Hilfsfunktionen
export function getValuesByGender(gender: Gender): BloodValue[] {
  return BLOOD_VALUES.filter(
    (v) => v.gender === 'all' || v.gender === gender
  )
}

export function getValuesByCategory(gender: Gender): Record<string, BloodValue[]> {
  const filtered = getValuesByGender(gender)
  return filtered.reduce((acc, value) => {
    if (!acc[value.category]) acc[value.category] = []
    acc[value.category].push(value)
    return acc
  }, {} as Record<string, BloodValue[]>)
}

export function getCycleDependentValues(): BloodValue[] {
  return BLOOD_VALUES.filter((v) => v.cycleDependent)
}
