'use no memo';

// src/constants/bloodValues.ts

export type Gender = 'male' | 'female' | 'diverse'

export interface BloodValue {
  id: string
  name: string
  shortName?: string
  category: string
  gender: 'all' | 'female' | 'male' // wer sieht diesen Wert
  cycleDependent?: boolean           // variiert je nach Zyklusphase
  units: string[]                    // mögliche Einheiten
  defaultUnit: string
  referenceRanges?: {
    male?: { min: number; max: number }
    female?: { min: number; max: number }
    all?: { min: number; max: number }
  }
  note?: string                      // Hinweis für den User
}

export const BLOOD_VALUE_CATEGORIES = [
  '🩸 Blutbild',
  '🍬 Stoffwechsel',
  '🫀 Herz & Gefäße',
  '🫁 Niere & Elektrolyte',
  '🟤 Leber & Galle',
  '🦋 Schilddrüse',
  '💊 Vitamine & Mineralstoffe',
  '⚡ Entzündung & Immunsystem',
  '🧬 Hormone (allgemein)',
  '♀️ Hormone (weiblich)',
  '♂️ Hormone (männlich)',
  '🦴 Knochen & Gelenke',
  '🧲 Eisenstoffwechsel',
  '🩺 Sonstiges',
]

export const BLOOD_VALUES: BloodValue[] = [

  // ─── 🩸 BLUTBILD ───────────────────────────────────────────────
  {
    id: 'hemoglobin',
    name: 'Hämoglobin',
    shortName: 'Hb',
    category: '🩸 Blutbild',
    gender: 'all',
    units: ['g/dL', 'g/L', 'mmol/L'],
    defaultUnit: 'g/dL',
    referenceRanges: {
      male: { min: 13.5, max: 17.5 },
      female: { min: 12.0, max: 16.0 },
    },
  },
  {
    id: 'hematocrit',
    name: 'Hämatokrit',
    shortName: 'Hkt',
    category: '🩸 Blutbild',
    gender: 'all',
    units: ['%', 'L/L'],
    defaultUnit: '%',
    referenceRanges: {
      male: { min: 40, max: 52 },
      female: { min: 36, max: 48 },
    },
  },
  {
    id: 'erythrocytes',
    name: 'Erythrozyten',
    shortName: 'RBC',
    category: '🩸 Blutbild',
    gender: 'all',
    units: ['Mio/µL', '10¹²/L'],
    defaultUnit: 'Mio/µL',
    referenceRanges: {
      male: { min: 4.4, max: 5.9 },
      female: { min: 3.8, max: 5.2 },
    },
  },
  {
    id: 'leukocytes',
    name: 'Leukozyten',
    shortName: 'WBC',
    category: '🩸 Blutbild',
    gender: 'all',
    units: ['Tsd/µL', '10⁹/L', '/µL'],
    defaultUnit: 'Tsd/µL',
    referenceRanges: { all: { min: 4.0, max: 10.0 } },
  },
  {
    id: 'thrombocytes',
    name: 'Thrombozyten',
    shortName: 'PLT',
    category: '🩸 Blutbild',
    gender: 'all',
    units: ['Tsd/µL', '10⁹/L'],
    defaultUnit: 'Tsd/µL',
    referenceRanges: { all: { min: 150, max: 400 } },
  },
  {
    id: 'mcv',
    name: 'MCV (mittl. Erythrozytenvolumen)',
    shortName: 'MCV',
    category: '🩸 Blutbild',
    gender: 'all',
    units: ['fL'],
    defaultUnit: 'fL',
    referenceRanges: { all: { min: 80, max: 100 } },
  },
  {
    id: 'mch',
    name: 'MCH (mittl. Hb-Gehalt)',
    shortName: 'MCH',
    category: '🩸 Blutbild',
    gender: 'all',
    units: ['pg'],
    defaultUnit: 'pg',
    referenceRanges: { all: { min: 27, max: 34 } },
  },
  {
    id: 'mchc',
    name: 'MCHC (mittl. Hb-Konzentration)',
    shortName: 'MCHC',
    category: '🩸 Blutbild',
    gender: 'all',
    units: ['g/dL', 'g/L'],
    defaultUnit: 'g/dL',
    referenceRanges: { all: { min: 32, max: 36 } },
  },
  {
    id: 'rdw',
    name: 'RDW (Erythrozytenverteilungsbreite)',
    shortName: 'RDW',
    category: '🩸 Blutbild',
    gender: 'all',
    units: ['%'],
    defaultUnit: '%',
    referenceRanges: { all: { min: 11.5, max: 14.5 } },
  },
  {
    id: 'neutrophils',
    name: 'Neutrophile',
    category: '🩸 Blutbild',
    gender: 'all',
    units: ['%', 'Tsd/µL'],
    defaultUnit: '%',
    referenceRanges: { all: { min: 50, max: 75 } },
  },
  {
    id: 'lymphocytes',
    name: 'Lymphozyten',
    category: '🩸 Blutbild',
    gender: 'all',
    units: ['%', 'Tsd/µL'],
    defaultUnit: '%',
    referenceRanges: { all: { min: 20, max: 45 } },
  },
  {
    id: 'monocytes',
    name: 'Monozyten',
    category: '🩸 Blutbild',
    gender: 'all',
    units: ['%', 'Tsd/µL'],
    defaultUnit: '%',
    referenceRanges: { all: { min: 2, max: 10 } },
  },
  {
    id: 'eosinophils',
    name: 'Eosinophile',
    category: '🩸 Blutbild',
    gender: 'all',
    units: ['%', 'Tsd/µL'],
    defaultUnit: '%',
    referenceRanges: { all: { min: 1, max: 6 } },
  },
  {
    id: 'basophils',
    name: 'Basophile',
    category: '🩸 Blutbild',
    gender: 'all',
    units: ['%', 'Tsd/µL'],
    defaultUnit: '%',
    referenceRanges: { all: { min: 0, max: 1 } },
  },

  // ─── 🍬 STOFFWECHSEL ───────────────────────────────────────────
  {
    id: 'glucose',
    name: 'Glukose (Blutzucker)',
    shortName: 'BZ',
    category: '🍬 Stoffwechsel',
    gender: 'all',
    units: ['mg/dL', 'mmol/L'],
    defaultUnit: 'mg/dL',
    referenceRanges: { all: { min: 70, max: 99 } },
    note: 'Nüchternwert (venöses Plasma)',
  },
  {
    id: 'glucose_2h',
    name: 'Glukose 2h (oGTT)',
    shortName: 'BZ 2h',
    category: '🍬 Stoffwechsel',
    gender: 'all',
    units: ['mg/dL', 'mmol/L'],
    defaultUnit: 'mg/dL',
    referenceRanges: { all: { min: 0, max: 140 } },
    note: '2-h-Wert im oralen Glukosetoleranztest; <140 mg/dL = normal',
  },
  {
    id: 'hba1c',
    name: 'HbA1c (Langzeitblutzucker)',
    shortName: 'HbA1c',
    category: '🍬 Stoffwechsel',
    gender: 'all',
    units: ['%', 'mmol/mol'],
    defaultUnit: '%',
    referenceRanges: { all: { min: 4.0, max: 5.7 } },
  },
  {
    id: 'fructosamine',
    name: 'Fruktosamin',
    shortName: 'Fruct',
    category: '🍬 Stoffwechsel',
    gender: 'all',
    units: ['µmol/L'],
    defaultUnit: 'µmol/L',
    referenceRanges: { all: { min: 205, max: 285 } },
    note: 'Kurzzeit-Blutzuckergedächtnis (ca. 2–3 Wochen)',
  },
  {
    id: 'insulin',
    name: 'Insulin (Nüchtern)',
    category: '🍬 Stoffwechsel',
    gender: 'all',
    units: ['µIU/mL', 'pmol/L'],
    defaultUnit: 'µIU/mL',
    referenceRanges: { all: { min: 2.6, max: 24.9 } },
  },
  {
    id: 'c_peptide',
    name: 'C-Peptid',
    shortName: 'C-Pep',
    category: '🍬 Stoffwechsel',
    gender: 'all',
    units: ['ng/mL', 'nmol/L'],
    defaultUnit: 'ng/mL',
    referenceRanges: { all: { min: 0.8, max: 3.8 } },
    note: 'Nüchternwert; Maß für körpereigene Insulinproduktion',
  },
  {
    id: 'proinsulin_intact',
    name: 'Proinsulin (intakt)',
    shortName: 'Proinsulin',
    category: '🍬 Stoffwechsel',
    gender: 'all',
    units: ['pmol/L'],
    defaultUnit: 'pmol/L',
    referenceRanges: { all: { min: 0, max: 11 } },
    note: 'Nüchternwert',
  },
  {
    id: 'homa_index',
    name: 'HOMA-Index (Insulinresistenz)',
    shortName: 'HOMA-IR',
    category: '🍬 Stoffwechsel',
    gender: 'all',
    units: ['index'],
    defaultUnit: 'index',
    referenceRanges: { all: { min: 0, max: 2.0 } },
    note: 'Berechnet aus Nüchterninsulin × Nüchternglukose / 405',
  },
  {
    id: 'cholesterol',
    name: 'Gesamtcholesterin',
    category: '🍬 Stoffwechsel',
    gender: 'all',
    units: ['mg/dL', 'mmol/L'],
    defaultUnit: 'mg/dL',
    referenceRanges: { all: { min: 0, max: 200 } },
  },
  {
    id: 'ldl',
    name: 'LDL-Cholesterin',
    shortName: 'LDL',
    category: '🍬 Stoffwechsel',
    gender: 'all',
    units: ['mg/dL', 'mmol/L'],
    defaultUnit: 'mg/dL',
    referenceRanges: { all: { min: 0, max: 116 } },
    note: 'Zielwert risikoadaptiert; bei erhöhtem kardiovaskulärem Risiko niedriger',
  },
  {
    id: 'hdl',
    name: 'HDL-Cholesterin',
    shortName: 'HDL',
    category: '🍬 Stoffwechsel',
    gender: 'all',
    units: ['mg/dL', 'mmol/L'],
    defaultUnit: 'mg/dL',
    referenceRanges: {
      male: { min: 40, max: 999 },
      female: { min: 50, max: 999 },
    },
    note: 'Untergrenze entscheidend; je höher desto günstiger',
  },
  {
    id: 'triglycerides',
    name: 'Triglyzeride',
    category: '🍬 Stoffwechsel',
    gender: 'all',
    units: ['mg/dL', 'mmol/L'],
    defaultUnit: 'mg/dL',
    referenceRanges: { all: { min: 0, max: 150 } },
  },
  {
    id: 'uric_acid',
    name: 'Harnsäure',
    category: '🍬 Stoffwechsel',
    gender: 'all',
    units: ['mg/dL', 'µmol/L'],
    defaultUnit: 'mg/dL',
    referenceRanges: {
      male: { min: 3.5, max: 7.2 },
      female: { min: 2.6, max: 6.0 },
    },
  },

  // ─── 🫀 HERZ & GEFÄSSE ─────────────────────────────────────────
  {
    id: 'crp',
    name: 'CRP (C-reaktives Protein)',
    shortName: 'CRP',
    category: '🫀 Herz & Gefäße',
    gender: 'all',
    units: ['mg/L', 'mg/dL'],
    defaultUnit: 'mg/L',
    referenceRanges: { all: { min: 0, max: 5 } },
  },
  {
    id: 'hs_crp',
    name: 'hsCRP (hochsensitiv)',
    shortName: 'hsCRP',
    category: '🫀 Herz & Gefäße',
    gender: 'all',
    units: ['mg/L'],
    defaultUnit: 'mg/L',
    referenceRanges: { all: { min: 0, max: 1 } },
    note: '<1 mg/L = niedriges kardiovaskuläres Risiko',
  },
  {
    id: 'troponin',
    name: 'Troponin hs (T/I)',
    shortName: 'hsTn',
    category: '🫀 Herz & Gefäße',
    gender: 'all',
    units: ['ng/L', 'pg/mL'],
    defaultUnit: 'ng/L',
    referenceRanges: {
      male: { min: 0, max: 22 },
      female: { min: 0, max: 14 },
    },
    note: '99. Perzentil; assay- und geschlechtsabhängig',
  },
  {
    id: 'bnp',
    name: 'BNP / NT-proBNP',
    category: '🫀 Herz & Gefäße',
    gender: 'all',
    units: ['pg/mL', 'ng/L'],
    defaultUnit: 'pg/mL',
    referenceRanges: { all: { min: 0, max: 100 } },
    note: 'BNP <100 pg/mL; NT-proBNP <125 pg/mL (unter 75 J.)',
  },
  {
    id: 'homocysteine',
    name: 'Homocystein',
    category: '🫀 Herz & Gefäße',
    gender: 'all',
    units: ['µmol/L'],
    defaultUnit: 'µmol/L',
    referenceRanges: { all: { min: 5, max: 15 } },
  },
  {
    id: 'lipoprotein_a',
    name: 'Lipoprotein (a)',
    shortName: 'Lp(a)',
    category: '🫀 Herz & Gefäße',
    gender: 'all',
    units: ['mg/dL', 'nmol/L'],
    defaultUnit: 'mg/dL',
    referenceRanges: { all: { min: 0, max: 30 } },
    note: 'Genetisch geprägt; erhöhtes kardiovaskuläres Risiko >30 mg/dL',
  },
  {
    id: 'apolipoprotein_a1',
    name: 'Apolipoprotein A1',
    shortName: 'ApoA1',
    category: '🫀 Herz & Gefäße',
    gender: 'all',
    units: ['mg/dL'],
    defaultUnit: 'mg/dL',
    referenceRanges: {
      male: { min: 110, max: 180 },
      female: { min: 120, max: 200 },
    },
  },
  {
    id: 'apolipoprotein_b',
    name: 'Apolipoprotein B',
    shortName: 'ApoB',
    category: '🫀 Herz & Gefäße',
    gender: 'all',
    units: ['mg/dL'],
    defaultUnit: 'mg/dL',
    referenceRanges: { all: { min: 60, max: 117 } },
    note: 'Zielwert risikoadaptiert',
  },

  // ─── 🫁 NIERE & ELEKTROLYTE ────────────────────────────────────
  {
    id: 'creatinine',
    name: 'Kreatinin',
    category: '🫁 Niere & Elektrolyte',
    gender: 'all',
    units: ['mg/dL', 'µmol/L'],
    defaultUnit: 'mg/dL',
    referenceRanges: {
      male: { min: 0.74, max: 1.35 },
      female: { min: 0.59, max: 1.04 },
    },
    note: 'Muskelmasse und Alter relevant; eGFR zusätzlich bewerten',
  },
  {
    id: 'creatinine_clearance',
    name: 'Kreatinin-Clearance',
    shortName: 'CrCl',
    category: '🫁 Niere & Elektrolyte',
    gender: 'all',
    units: ['mL/min'],
    defaultUnit: 'mL/min',
    referenceRanges: {
      male: { min: 97, max: 137 },
      female: { min: 88, max: 128 },
    },
    note: 'Altersabhängig abnehmend; Körperoberfläche beachten',
  },
  {
    id: 'gfr',
    name: 'GFR (Nierenfiltration)',
    shortName: 'eGFR',
    category: '🫁 Niere & Elektrolyte',
    gender: 'all',
    units: ['mL/min/1,73m²'],
    defaultUnit: 'mL/min/1,73m²',
    referenceRanges: { all: { min: 60, max: 120 } },
  },
  {
    id: 'cystatin_c',
    name: 'Cystatin C',
    shortName: 'CysC',
    category: '🫁 Niere & Elektrolyte',
    gender: 'all',
    units: ['mg/L'],
    defaultUnit: 'mg/L',
    referenceRanges: { all: { min: 0.6, max: 1.0 } },
    note: 'Muskelmassenunabhängiger Nierenmarker; altersabhängig',
  },
  {
    id: 'urea',
    name: 'Harnstoff',
    category: '🫁 Niere & Elektrolyte',
    gender: 'all',
    units: ['mg/dL', 'mmol/L'],
    defaultUnit: 'mg/dL',
    referenceRanges: { all: { min: 15, max: 40 } },
  },
  {
    id: 'sodium',
    name: 'Natrium',
    shortName: 'Na⁺',
    category: '🫁 Niere & Elektrolyte',
    gender: 'all',
    units: ['mmol/L', 'mEq/L'],
    defaultUnit: 'mmol/L',
    referenceRanges: { all: { min: 136, max: 145 } },
  },
  {
    id: 'potassium',
    name: 'Kalium',
    shortName: 'K⁺',
    category: '🫁 Niere & Elektrolyte',
    gender: 'all',
    units: ['mmol/L', 'mEq/L'],
    defaultUnit: 'mmol/L',
    referenceRanges: { all: { min: 3.5, max: 5.0 } },
  },
  {
    id: 'calcium',
    name: 'Kalzium',
    shortName: 'Ca²⁺',
    category: '🫁 Niere & Elektrolyte',
    gender: 'all',
    units: ['mmol/L', 'mg/dL', 'mEq/L'],
    defaultUnit: 'mmol/L',
    referenceRanges: { all: { min: 2.10, max: 2.55 } },
  },
  {
    id: 'magnesium',
    name: 'Magnesium',
    shortName: 'Mg²⁺',
    category: '🫁 Niere & Elektrolyte',
    gender: 'all',
    units: ['mmol/L', 'mg/dL', 'mEq/L'],
    defaultUnit: 'mmol/L',
    referenceRanges: { all: { min: 0.75, max: 0.95 } },
  },
  {
    id: 'phosphate',
    name: 'Phosphat',
    category: '🫁 Niere & Elektrolyte',
    gender: 'all',
    units: ['mmol/L', 'mg/dL'],
    defaultUnit: 'mmol/L',
    referenceRanges: { all: { min: 0.97, max: 1.45 } },
  },
  {
    id: 'chloride',
    name: 'Chlorid',
    shortName: 'Cl⁻',
    category: '🫁 Niere & Elektrolyte',
    gender: 'all',
    units: ['mmol/L', 'mEq/L'],
    defaultUnit: 'mmol/L',
    referenceRanges: { all: { min: 98, max: 106 } },
  },
  {
    id: 'osmolality',
    name: 'Osmolalität (Serum)',
    shortName: 'Osm',
    category: '🫁 Niere & Elektrolyte',
    gender: 'all',
    units: ['mOsm/kg'],
    defaultUnit: 'mOsm/kg',
    referenceRanges: { all: { min: 275, max: 295 } },
  },

  // ─── 🟤 LEBER & GALLE ─────────────────────────────────────────
  {
    id: 'got',
    name: 'GOT / AST',
    shortName: 'GOT',
    category: '🟤 Leber & Galle',
    gender: 'all',
    units: ['U/L', 'µkat/L'],
    defaultUnit: 'U/L',
    referenceRanges: {
      male: { min: 8, max: 48 },
      female: { min: 8, max: 43 },
    },
  },
  {
    id: 'gpt',
    name: 'GPT / ALT',
    shortName: 'GPT',
    category: '🟤 Leber & Galle',
    gender: 'all',
    units: ['U/L', 'µkat/L'],
    defaultUnit: 'U/L',
    referenceRanges: {
      male: { min: 7, max: 55 },
      female: { min: 7, max: 45 },
    },
  },
  {
    id: 'ggt',
    name: 'GGT (Gamma-GT)',
    shortName: 'GGT',
    category: '🟤 Leber & Galle',
    gender: 'all',
    units: ['U/L', 'µkat/L'],
    defaultUnit: 'U/L',
    referenceRanges: {
      male: { min: 8, max: 61 },
      female: { min: 5, max: 36 },
    },
  },
  {
    id: 'gldh',
    name: 'GLDH (Glutamatdehydrogenase)',
    shortName: 'GLDH',
    category: '🟤 Leber & Galle',
    gender: 'all',
    units: ['U/L'],
    defaultUnit: 'U/L',
    referenceRanges: {
      male: { min: 0, max: 7 },
      female: { min: 0, max: 5 },
    },
    note: 'Spezifischer Marker für Leberzellschaden (Mitochondrien)',
  },
  {
    id: 'ap',
    name: 'Alkalische Phosphatase',
    shortName: 'AP',
    category: '🟤 Leber & Galle',
    gender: 'all',
    units: ['U/L'],
    defaultUnit: 'U/L',
    referenceRanges: {
      male: { min: 40, max: 129 },
      female: { min: 35, max: 104 },
    },
  },
  {
    id: 'cholinesterase',
    name: 'Cholinesterase',
    shortName: 'CHE',
    category: '🟤 Leber & Galle',
    gender: 'all',
    units: ['U/L', 'kU/L'],
    defaultUnit: 'U/L',
    referenceRanges: { all: { min: 5320, max: 12920 } },
    note: 'Maß für die Syntheseleistung der Leber; stark methodenabhängig',
  },
  {
    id: 'bilirubin_total',
    name: 'Bilirubin (gesamt)',
    category: '🟤 Leber & Galle',
    gender: 'all',
    units: ['mg/dL', 'µmol/L'],
    defaultUnit: 'mg/dL',
    referenceRanges: { all: { min: 0.1, max: 1.2 } },
  },
  {
    id: 'bilirubin_direct',
    name: 'Bilirubin (direkt)',
    category: '🟤 Leber & Galle',
    gender: 'all',
    units: ['mg/dL', 'µmol/L'],
    defaultUnit: 'mg/dL',
    referenceRanges: { all: { min: 0, max: 0.3 } },
  },
  {
    id: 'albumin',
    name: 'Albumin',
    category: '🟤 Leber & Galle',
    gender: 'all',
    units: ['g/dL', 'g/L'],
    defaultUnit: 'g/dL',
    referenceRanges: { all: { min: 3.5, max: 5.5 } },
  },
  {
    id: 'total_protein',
    name: 'Gesamtprotein',
    category: '🟤 Leber & Galle',
    gender: 'all',
    units: ['g/dL', 'g/L'],
    defaultUnit: 'g/dL',
    referenceRanges: { all: { min: 6.0, max: 7.8 } },
  },
  {
    id: 'haptoglobin',
    name: 'Haptoglobin',
    shortName: 'Hapto',
    category: '🟤 Leber & Galle',
    gender: 'all',
    units: ['g/L', 'mg/dL'],
    defaultUnit: 'g/L',
    referenceRanges: { all: { min: 0.3, max: 2.0 } },
    note: 'Bei Hämolyse erniedrigt; Akute-Phase-Protein',
  },
  {
    id: 'lactate',
    name: 'Laktat',
    shortName: 'Lac',
    category: '🟤 Leber & Galle',
    gender: 'all',
    units: ['mmol/L'],
    defaultUnit: 'mmol/L',
    referenceRanges: { all: { min: 0.5, max: 2.2 } },
    note: 'Venös; Stauung vor Abnahme vermeiden',
  },
  {
    id: 'ammonia',
    name: 'Ammoniak',
    shortName: 'NH₃',
    category: '🟤 Leber & Galle',
    gender: 'all',
    units: ['µmol/L'],
    defaultUnit: 'µmol/L',
    referenceRanges: { all: { min: 11, max: 35 } },
    note: 'Präanalytisch kritisch – sofortige Verarbeitung nötig',
  },
  {
    id: 'gastrin',
    name: 'Gastrin',
    category: '🟤 Leber & Galle',
    gender: 'all',
    units: ['pg/mL'],
    defaultUnit: 'pg/mL',
    referenceRanges: { all: { min: 0, max: 100 } },
    note: 'Nüchternwert; PPI-Einnahme stark erhöhend',
  },

  // ─── 🦋 SCHILDDRÜSE ────────────────────────────────────────────
  {
    id: 'tsh',
    name: 'TSH',
    category: '🦋 Schilddrüse',
    gender: 'all',
    units: ['mIU/L', 'µIU/mL'],
    defaultUnit: 'mIU/L',
    referenceRanges: { all: { min: 0.4, max: 4.0 } },
  },
  {
    id: 'ft3',
    name: 'Freies T3 (fT3)',
    shortName: 'fT3',
    category: '🦋 Schilddrüse',
    gender: 'all',
    units: ['pmol/L', 'pg/mL', 'ng/dL'],
    defaultUnit: 'pmol/L',
    referenceRanges: { all: { min: 3.1, max: 6.8 } },
    note: 'Assayabhängig',
  },
  {
    id: 'ft4',
    name: 'Freies T4 (fT4)',
    shortName: 'fT4',
    category: '🦋 Schilddrüse',
    gender: 'all',
    units: ['pmol/L', 'ng/dL'],
    defaultUnit: 'pmol/L',
    referenceRanges: { all: { min: 12, max: 22 } },
    note: 'Assayabhängig',
  },
  {
    id: 'reverse_t3',
    name: 'Reverses T3 (rT3)',
    shortName: 'rT3',
    category: '🦋 Schilddrüse',
    gender: 'all',
    units: ['ng/dL'],
    defaultUnit: 'ng/dL',
    referenceRanges: { all: { min: 9.2, max: 24.1 } },
    note: 'Assayabhängig; erhöht bei chronischem Stress/Krankheit',
  },
  {
    id: 'thyroglobulin',
    name: 'Thyreoglobulin',
    shortName: 'Tg',
    category: '🦋 Schilddrüse',
    gender: 'all',
    units: ['ng/mL'],
    defaultUnit: 'ng/mL',
    referenceRanges: { all: { min: 1.5, max: 38.5 } },
    note: 'Sinnvoll nur bei vorhandener Schilddrüse; Tg-AK beachten',
  },
  {
    id: 'tpo_ak',
    name: 'TPO-Antikörper',
    shortName: 'TPO-AK',
    category: '🦋 Schilddrüse',
    gender: 'all',
    units: ['IU/mL', 'U/mL'],
    defaultUnit: 'IU/mL',
    referenceRanges: { all: { min: 0, max: 34 } },
    note: 'Negativgrenze assayabhängig',
  },
  {
    id: 'thyroglobulin_antibody',
    name: 'Thyreoglobulin-Antikörper',
    shortName: 'Tg-AK',
    category: '🦋 Schilddrüse',
    gender: 'all',
    units: ['IU/mL'],
    defaultUnit: 'IU/mL',
    referenceRanges: { all: { min: 0, max: 4 } },
    note: 'Negativgrenze assayabhängig',
  },
  {
    id: 'trak',
    name: 'TSH-Rezeptor-Antikörper',
    shortName: 'TRAK',
    category: '🦋 Schilddrüse',
    gender: 'all',
    units: ['IU/L'],
    defaultUnit: 'IU/L',
    referenceRanges: { all: { min: 0, max: 1.75 } },
    note: 'Diagnostisch bei Morbus Basedow; assayabhängig',
  },

  // ─── 💊 VITAMINE & MINERALSTOFFE ───────────────────────────────
  {
    id: 'vitamin_d',
    name: 'Vitamin D (25-OH)',
    shortName: 'Vit. D',
    category: '💊 Vitamine & Mineralstoffe',
    gender: 'all',
    units: ['ng/mL', 'nmol/L'],
    defaultUnit: 'ng/mL',
    referenceRanges: { all: { min: 20, max: 50 } },
    note: 'Laborbereich 20–50 ng/mL; viele Experten empfehlen 30–60 ng/mL als Ziel',
  },
  {
    id: 'vitamin_d_1_25oh',
    name: 'Vitamin D3 (1,25-OH₂)',
    shortName: '1,25-OH₂-D',
    category: '💊 Vitamine & Mineralstoffe',
    gender: 'all',
    units: ['pg/mL', 'pmol/L'],
    defaultUnit: 'pg/mL',
    referenceRanges: { all: { min: 18, max: 72 } },
    note: 'Aktives Calcitriol; nicht Speicherstatus',
  },
  {
    id: 'vitamin_b12',
    name: 'Vitamin B12',
    shortName: 'Vit. B12',
    category: '💊 Vitamine & Mineralstoffe',
    gender: 'all',
    units: ['pg/mL', 'pmol/L'],
    defaultUnit: 'pg/mL',
    referenceRanges: { all: { min: 200, max: 900 } },
    note: 'Bei Grenzwerten Holo-Transcobalamin (aktives B12) bestimmen',
  },
  {
    id: 'holo_tc',
    name: 'Holo-Transcobalamin (aktives B12)',
    shortName: 'Holo-TC',
    category: '💊 Vitamine & Mineralstoffe',
    gender: 'all',
    units: ['pmol/L'],
    defaultUnit: 'pmol/L',
    referenceRanges: { all: { min: 35, max: 150 } },
    note: 'Funktionell relevante Fraktion des Vitamin B12',
  },
  {
    id: 'methylmalonic_acid',
    name: 'Methylmalonsäure (MMA)',
    shortName: 'MMA',
    category: '💊 Vitamine & Mineralstoffe',
    gender: 'all',
    units: ['µmol/L', 'nmol/L'],
    defaultUnit: 'µmol/L',
    referenceRanges: { all: { min: 0, max: 0.4 } },
    note: 'Funktioneller B12-Mangel-Marker; Nierenfunktion beachten',
  },
  {
    id: 'folate',
    name: 'Folsäure',
    category: '💊 Vitamine & Mineralstoffe',
    gender: 'all',
    units: ['ng/mL', 'nmol/L'],
    defaultUnit: 'ng/mL',
    referenceRanges: { all: { min: 3.0, max: 20.0 } },
  },
  {
    id: 'vitamin_b1',
    name: 'Vitamin B1 (Thiamin)',
    shortName: 'Vit. B1',
    category: '💊 Vitamine & Mineralstoffe',
    gender: 'all',
    units: ['nmol/L', 'µg/L'],
    defaultUnit: 'nmol/L',
    referenceRanges: { all: { min: 70, max: 180 } },
    note: 'Vollblut (Thiaminpyrophosphat bevorzugt)',
  },
  {
    id: 'vitamin_b2',
    name: 'Vitamin B2 (Riboflavin)',
    shortName: 'Vit. B2',
    category: '💊 Vitamine & Mineralstoffe',
    gender: 'all',
    units: ['µg/L', 'nmol/L'],
    defaultUnit: 'µg/L',
    referenceRanges: { all: { min: 5, max: 50 } },
    note: 'Methodenabhängig',
  },
  {
    id: 'vitamin_b6',
    name: 'Vitamin B6 (Pyridoxin)',
    shortName: 'Vit. B6',
    category: '💊 Vitamine & Mineralstoffe',
    gender: 'all',
    units: ['µg/L', 'nmol/L'],
    defaultUnit: 'µg/L',
    referenceRanges: { all: { min: 5, max: 50 } },
    note: 'Als PLP (Pyridoxal-5-Phosphat) im Plasma',
  },
  {
    id: 'vitamin_a',
    name: 'Vitamin A (Retinol)',
    shortName: 'Vit. A',
    category: '💊 Vitamine & Mineralstoffe',
    gender: 'all',
    units: ['µg/dL', 'µmol/L'],
    defaultUnit: 'µg/dL',
    referenceRanges: { all: { min: 20, max: 60 } },
  },
  {
    id: 'vitamin_e',
    name: 'Vitamin E (Tocopherol)',
    shortName: 'Vit. E',
    category: '💊 Vitamine & Mineralstoffe',
    gender: 'all',
    units: ['mg/L', 'µmol/L'],
    defaultUnit: 'mg/L',
    referenceRanges: { all: { min: 5.5, max: 17.0 } },
    note: 'Alpha-Tocopherol; lipidabhängig',
  },
  {
    id: 'vitamin_k',
    name: 'Vitamin K (Phyllochinon)',
    shortName: 'Vit. K',
    category: '💊 Vitamine & Mineralstoffe',
    gender: 'all',
    units: ['ng/mL', 'nmol/L'],
    defaultUnit: 'ng/mL',
    referenceRanges: { all: { min: 0.1, max: 2.2 } },
    note: 'Methodenabhängig; nicht für Gerinnungsmonitoring unter Marcumar',
  },
  {
    id: 'ubiquinone_q10',
    name: 'Coenzym Q10 (Ubiquinon)',
    shortName: 'Q10',
    category: '💊 Vitamine & Mineralstoffe',
    gender: 'all',
    units: ['mg/L', 'µmol/L'],
    defaultUnit: 'mg/L',
    referenceRanges: { all: { min: 0.5, max: 1.5 } },
    note: 'Lipidabhängig; unter Statintherapie häufig erniedrigt',
  },
  {
    id: 'zinc',
    name: 'Zink',
    category: '💊 Vitamine & Mineralstoffe',
    gender: 'all',
    units: ['µg/dL', 'µmol/L'],
    defaultUnit: 'µg/dL',
    referenceRanges: { all: { min: 70, max: 120 } },
  },
  {
    id: 'selenium',
    name: 'Selen',
    category: '💊 Vitamine & Mineralstoffe',
    gender: 'all',
    units: ['µg/L', 'nmol/L'],
    defaultUnit: 'µg/L',
    referenceRanges: { all: { min: 70, max: 150 } },
  },
  {
    id: 'copper',
    name: 'Kupfer',
    shortName: 'Cu',
    category: '💊 Vitamine & Mineralstoffe',
    gender: 'all',
    units: ['µg/dL', 'µmol/L'],
    defaultUnit: 'µg/dL',
    referenceRanges: { all: { min: 70, max: 140 } },
  },

  // ─── ⚡ ENTZÜNDUNG & IMMUNSYSTEM ───────────────────────────────
  {
    id: 'esr',
    name: 'BSG (Blutsenkungsgeschwindigkeit)',
    shortName: 'BSG',
    category: '⚡ Entzündung & Immunsystem',
    gender: 'all',
    units: ['mm/h'],
    defaultUnit: 'mm/h',
    referenceRanges: {
      male: { min: 0, max: 15 },
      female: { min: 0, max: 20 },
    },
  },
  {
    id: 'pct',
    name: 'Procalcitonin',
    shortName: 'PCT',
    category: '⚡ Entzündung & Immunsystem',
    gender: 'all',
    units: ['ng/mL', 'µg/L'],
    defaultUnit: 'ng/mL',
    referenceRanges: { all: { min: 0, max: 0.05 } },
    note: '<0.05 ng/mL: kein Hinweis auf bakterielle Infektion',
  },
  {
    id: 'il6',
    name: 'Interleukin-6',
    shortName: 'IL-6',
    category: '⚡ Entzündung & Immunsystem',
    gender: 'all',
    units: ['pg/mL'],
    defaultUnit: 'pg/mL',
    referenceRanges: { all: { min: 0, max: 7 } },
  },
  {
    id: 'il2_receptor',
    name: 'IL-2-Rezeptor (löslich)',
    shortName: 'sIL-2R',
    category: '⚡ Entzündung & Immunsystem',
    gender: 'all',
    units: ['U/mL'],
    defaultUnit: 'U/mL',
    referenceRanges: { all: { min: 223, max: 710 } },
    note: 'Erhöht bei Sarkoidose, Lymphomen; assayabhängig',
  },
  {
    id: 'iga',
    name: 'Immunglobulin A (IgA)',
    shortName: 'IgA',
    category: '⚡ Entzündung & Immunsystem',
    gender: 'all',
    units: ['g/L', 'mg/dL'],
    defaultUnit: 'g/L',
    referenceRanges: { all: { min: 0.7, max: 4.0 } },
  },
  {
    id: 'igg',
    name: 'Immunglobulin G (IgG)',
    shortName: 'IgG',
    category: '⚡ Entzündung & Immunsystem',
    gender: 'all',
    units: ['g/L', 'mg/dL'],
    defaultUnit: 'g/L',
    referenceRanges: { all: { min: 7.0, max: 16.0 } },
  },
  {
    id: 'igm',
    name: 'Immunglobulin M (IgM)',
    shortName: 'IgM',
    category: '⚡ Entzündung & Immunsystem',
    gender: 'all',
    units: ['g/L', 'mg/dL'],
    defaultUnit: 'g/L',
    referenceRanges: {
      male: { min: 0.4, max: 2.3 },
      female: { min: 0.4, max: 2.8 },
    },
  },
  {
    id: 'ige_total',
    name: 'Immunglobulin E gesamt (IgE)',
    shortName: 'IgE',
    category: '⚡ Entzündung & Immunsystem',
    gender: 'all',
    units: ['IU/mL', 'kU/L'],
    defaultUnit: 'IU/mL',
    referenceRanges: { all: { min: 0, max: 100 } },
    note: 'Stark allergie- und altersabhängig',
  },
  {
    id: 'ecp',
    name: 'Eosinophiles kationisches Protein (ECP)',
    shortName: 'ECP',
    category: '⚡ Entzündung & Immunsystem',
    gender: 'all',
    units: ['µg/L'],
    defaultUnit: 'µg/L',
    referenceRanges: { all: { min: 0, max: 24 } },
    note: 'Marker für eosinophile Entzündung (Asthma, Allergie)',
  },
  {
    id: 'transglutaminase_iga',
    name: 'Transglutaminase-AK IgA (tTG)',
    shortName: 'tTG-IgA',
    category: '⚡ Entzündung & Immunsystem',
    gender: 'all',
    units: ['U/mL'],
    defaultUnit: 'U/mL',
    referenceRanges: { all: { min: 0, max: 7 } },
    note: 'Zöliakie-Screening; Negativgrenze assayabhängig',
  },
  {
    id: 'rf_igm',
    name: 'Rheumafaktor IgM (quantitativ)',
    shortName: 'RF IgM',
    category: '⚡ Entzündung & Immunsystem',
    gender: 'all',
    units: ['IU/mL'],
    defaultUnit: 'IU/mL',
    referenceRanges: { all: { min: 0, max: 14 } },
    note: 'Negativgrenze assayabhängig',
  },
  {
    id: 'rf_iga_igg',
    name: 'Rheumafaktor IgA/IgG',
    shortName: 'RF IgA/G',
    category: '⚡ Entzündung & Immunsystem',
    gender: 'all',
    units: ['U/mL'],
    defaultUnit: 'U/mL',
    referenceRanges: { all: { min: 0, max: 20 } },
    note: 'Negativgrenze assayabhängig',
  },
  {
    id: 'c1_esterase_inhibitor',
    name: 'C1-Esterase-Inhibitor',
    shortName: 'C1-INH',
    category: '⚡ Entzündung & Immunsystem',
    gender: 'all',
    units: ['mg/dL', '%'],
    defaultUnit: 'mg/dL',
    referenceRanges: { all: { min: 21, max: 39 } },
    note: 'Erniedrigt bei hereditärem Angioödem (HAE)',
  },

  // ─── 🧬 HORMONE (ALLGEMEIN) ────────────────────────────────────
  {
    id: 'cortisol',
    name: 'Cortisol (Morgen)',
    category: '🧬 Hormone (allgemein)',
    gender: 'all',
    units: ['µg/dL', 'nmol/L'],
    defaultUnit: 'µg/dL',
    referenceRanges: { all: { min: 6.2, max: 19.4 } },
    note: 'Morgenblut (ca. 8 Uhr); tageszeitabhängig',
  },
  {
    id: 'cortisol_midnight',
    name: 'Cortisol (Mitternacht)',
    shortName: 'Cort 24h',
    category: '🧬 Hormone (allgemein)',
    gender: 'all',
    units: ['µg/dL', 'nmol/L'],
    defaultUnit: 'µg/dL',
    referenceRanges: { all: { min: 0, max: 5 } },
    note: 'Diagnostisch für Cushing-Syndrom',
  },
  {
    id: 'acth',
    name: 'ACTH (adrenokortikotropes Hormon)',
    shortName: 'ACTH',
    category: '🧬 Hormone (allgemein)',
    gender: 'all',
    units: ['pg/mL', 'pmol/L'],
    defaultUnit: 'pg/mL',
    referenceRanges: { all: { min: 7.2, max: 63.3 } },
    note: 'Morgenblut; präanalytisch empfindlich (Eis, sofort zentrifugieren)',
  },
  {
    id: 'adh_vasopressin',
    name: 'ADH / Vasopressin',
    shortName: 'ADH',
    category: '🧬 Hormone (allgemein)',
    gender: 'all',
    units: ['pg/mL'],
    defaultUnit: 'pg/mL',
    referenceRanges: { all: { min: 0, max: 6.7 } },
    note: 'Osmolalitätsabhängig; Copeptin als stabilerer Alternativmarker',
  },
  {
    id: 'aldosterone',
    name: 'Aldosteron',
    shortName: 'Aldo',
    category: '🧬 Hormone (allgemein)',
    gender: 'all',
    units: ['ng/dL', 'pmol/L'],
    defaultUnit: 'ng/dL',
    referenceRanges: { all: { min: 3, max: 16 } },
    note: 'Aufrecht/morgens; Salzstatus und Medikation berücksichtigen',
  },
  {
    id: 'renin',
    name: 'Renin (aktiv)',
    category: '🧬 Hormone (allgemein)',
    gender: 'all',
    units: ['ng/L', 'µIU/mL'],
    defaultUnit: 'ng/L',
    referenceRanges: { all: { min: 2.8, max: 39.9 } },
    note: 'Lage, Salzstatus und Medikamente entscheidend',
  },
  {
    id: 'dhea_s',
    name: 'DHEA-S',
    category: '🧬 Hormone (allgemein)',
    gender: 'all',
    units: ['µg/dL', 'µmol/L'],
    defaultUnit: 'µg/dL',
    referenceRanges: {
      male: { min: 80, max: 560 },
      female: { min: 35, max: 430 },
    },
    note: 'Stark altersabhängig; mit 60+ deutlich niedrigere Werte normal',
  },
  {
    id: 'dhea_free',
    name: 'DHEA (frei)',
    shortName: 'DHEA frei',
    category: '🧬 Hormone (allgemein)',
    gender: 'all',
    units: ['pg/mL'],
    defaultUnit: 'pg/mL',
    referenceRanges: {
      male: { min: 2, max: 18 },
      female: { min: 1, max: 10 },
    },
    note: 'Methoden- und altersabhängig; Einheit/Assay prüfen',
  },
  {
    id: 'androstenedione',
    name: 'Androstendion',
    shortName: 'A4',
    category: '🧬 Hormone (allgemein)',
    gender: 'all',
    units: ['ng/mL', 'nmol/L'],
    defaultUnit: 'ng/mL',
    referenceRanges: {
      male: { min: 0.6, max: 3.1 },
      female: { min: 0.3, max: 4.5 },
    },
    note: 'Zyklus- und altersabhängig bei Frauen',
  },
  {
    id: 'insulin_like_growth_factor',
    name: 'IGF-1 (Somatomedin C)',
    shortName: 'IGF-1',
    category: '🧬 Hormone (allgemein)',
    gender: 'all',
    units: ['ng/mL', 'nmol/L'],
    defaultUnit: 'ng/mL',
    referenceRanges: {
      male: { min: 60, max: 310 },
      female: { min: 65, max: 320 },
    },
    note: 'Stark alters- und geschlechtsabhängig',
  },
  {
    id: 'igfbp3',
    name: 'IGF-Bindeprotein 3 (IGFBP-3)',
    shortName: 'IGFBP-3',
    category: '🧬 Hormone (allgemein)',
    gender: 'all',
    units: ['mg/L'],
    defaultUnit: 'mg/L',
    referenceRanges: { all: { min: 2.7, max: 7.8 } },
    note: 'Stark altersabhängig; zusammen mit IGF-1 bewerten',
  },
  {
    id: 'growth_hormone',
    name: 'Wachstumshormon (GH/HGH)',
    shortName: 'GH',
    category: '🧬 Hormone (allgemein)',
    gender: 'all',
    units: ['ng/mL', 'µg/L', 'mIU/L'],
    defaultUnit: 'ng/mL',
    referenceRanges: { all: { min: 0, max: 10 } },
    note: 'Pulsatil; Stimulationstest für sichere Diagnose nötig',
  },
  {
    id: 'prolactin',
    name: 'Prolaktin',
    category: '🧬 Hormone (allgemein)',
    gender: 'all',
    units: ['ng/mL', 'mIU/L', 'µg/L'],
    defaultUnit: 'ng/mL',
    referenceRanges: {
      male: { min: 4.0, max: 15.2 },
      female: { min: 4.8, max: 23.3 },
    },
    cycleDependent: true,
    note: 'Stress, Medikamente und Schwangerschaft/Stillzeit erhöhen Prolaktin',
  },
  {
    id: 'leptin',
    name: 'Leptin',
    category: '🧬 Hormone (allgemein)',
    gender: 'all',
    units: ['ng/mL'],
    defaultUnit: 'ng/mL',
    referenceRanges: {
      male: { min: 0.5, max: 12 },
      female: { min: 3, max: 30 },
    },
    note: 'Stark abhängig von BMI, Geschlecht und Fettmasse',
  },
  {
    id: 'serotonin',
    name: 'Serotonin',
    shortName: '5-HT',
    category: '🧬 Hormone (allgemein)',
    gender: 'all',
    units: ['ng/mL'],
    defaultUnit: 'ng/mL',
    referenceRanges: { all: { min: 50, max: 200 } },
    note: 'Serum; Thrombozyten beeinflussen den Wert',
  },
  {
    id: 'calcitonin',
    name: 'Calcitonin',
    shortName: 'CT',
    category: '🧬 Hormone (allgemein)',
    gender: 'all',
    units: ['pg/mL'],
    defaultUnit: 'pg/mL',
    referenceRanges: {
      male: { min: 0, max: 8.4 },
      female: { min: 0, max: 5.0 },
    },
    note: 'Assay- und geschlechtsabhängig; Tumormarker für medulläres Schilddrüsen-CA',
  },
  {
    id: 'insulin_fasting',
    name: 'Nüchterninsulin',
    category: '🧬 Hormone (allgemein)',
    gender: 'all',
    units: ['µIU/mL', 'pmol/L'],
    defaultUnit: 'µIU/mL',
    referenceRanges: { all: { min: 2.6, max: 24.9 } },
  },

  // ─── ♀️ HORMONE (WEIBLICH) ─────────────────────────────────────
  {
    id: 'estradiol',
    name: 'Östradiol (E2)',
    shortName: 'E2',
    category: '♀️ Hormone (weiblich)',
    gender: 'female',
    cycleDependent: true,
    units: ['pg/mL', 'pmol/L'],
    defaultUnit: 'pg/mL',
    referenceRanges: { female: { min: 12, max: 498 } },
    note: 'Stark zyklusabhängig (Follikel 12–166, Ovulation 86–498, Luteal 44–211 pg/mL)',
  },
  {
    id: 'estrone',
    name: 'Östron (E1)',
    shortName: 'E1',
    category: '♀️ Hormone (weiblich)',
    gender: 'female',
    cycleDependent: true,
    units: ['pg/mL', 'pmol/L'],
    defaultUnit: 'pg/mL',
    referenceRanges: { female: { min: 17, max: 250 } },
    note: 'Zyklusabhängig (Follikel 17–200, Luteal 50–250 pg/mL)',
  },
  {
    id: 'estriol',
    name: 'Östriol (E3)',
    shortName: 'E3',
    category: '♀️ Hormone (weiblich)',
    gender: 'female',
    units: ['ng/mL', 'nmol/L'],
    defaultUnit: 'ng/mL',
    note: 'Relevant in der Schwangerschaft; außerhalb sehr niedrig',
  },
  {
    id: 'progesterone',
    name: 'Progesteron',
    category: '♀️ Hormone (weiblich)',
    gender: 'female',
    cycleDependent: true,
    units: ['ng/mL', 'nmol/L'],
    defaultUnit: 'ng/mL',
    referenceRanges: { female: { min: 0.1, max: 24.0 } },
    note: 'Stark zyklusabhängig (Follikel 0.1–0.9, Luteal 1.8–24.0 ng/mL)',
  },
  {
    id: 'progesterone_17oh',
    name: '17-OH-Progesteron',
    shortName: '17-OHP',
    category: '♀️ Hormone (weiblich)',
    gender: 'female',
    cycleDependent: true,
    units: ['ng/mL', 'nmol/L'],
    defaultUnit: 'ng/mL',
    referenceRanges: { female: { min: 0.1, max: 2.3 } },
    note: 'Zyklusphasenabhängig; Screening auf AGS (adrenogenitales Syndrom)',
  },
  {
    id: 'lh',
    name: 'LH (Luteinisierendes Hormon)',
    shortName: 'LH',
    category: '♀️ Hormone (weiblich)',
    gender: 'female',
    cycleDependent: true,
    units: ['IU/L', 'mIU/mL'],
    defaultUnit: 'IU/L',
    referenceRanges: { female: { min: 2.4, max: 95.6 } },
    note: 'Stark zyklusabhängig (Follikel 2.4–12.6, Ovulation 14–95.6, Luteal 1.0–11.4 IU/L)',
  },
  {
    id: 'fsh',
    name: 'FSH (Follikelstimulierendes Hormon)',
    shortName: 'FSH',
    category: '♀️ Hormone (weiblich)',
    gender: 'female',
    cycleDependent: true,
    units: ['IU/L', 'mIU/mL'],
    defaultUnit: 'IU/L',
    referenceRanges: { female: { min: 1.7, max: 21.5 } },
    note: 'Stark zyklusabhängig (Follikel 3.5–12.5, Ovulation 4.7–21.5 IU/L)',
  },
  {
    id: 'amh',
    name: 'AMH (Anti-Müller-Hormon)',
    shortName: 'AMH',
    category: '♀️ Hormone (weiblich)',
    gender: 'female',
    units: ['ng/mL', 'pmol/L'],
    defaultUnit: 'ng/mL',
    referenceRanges: { female: { min: 0.7, max: 7.3 } },
    note: 'Stark altersabhängig (20–24 J.: 1.7–7.3, 40–44 J.: 0.1–2.5 ng/mL)',
  },
  {
    id: 'fai',
    name: 'Freier Androgenindex (FAI)',
    shortName: 'FAI',
    category: '♀️ Hormone (weiblich)',
    gender: 'female',
    units: ['index'],
    defaultUnit: 'index',
    referenceRanges: { female: { min: 0.5, max: 7.0 } },
    note: 'Berechnet aus Testosteron × 100 / SHBG; Hyperandrogenismus >7',
  },
  {
    id: 'shbg_female',
    name: 'SHBG',
    category: '♀️ Hormone (weiblich)',
    gender: 'female',
    units: ['nmol/L'],
    defaultUnit: 'nmol/L',
    referenceRanges: { female: { min: 18, max: 144 } },
  },
  {
    id: 'free_testosterone_female',
    name: 'Freies Testosteron (Frau)',
    category: '♀️ Hormone (weiblich)',
    gender: 'female',
    units: ['pg/mL', 'pmol/L'],
    defaultUnit: 'pg/mL',
    referenceRanges: { female: { min: 0.5, max: 6.5 } },
  },
  {
    id: 'total_testosterone_female',
    name: 'Gesamttestosteron (Frau)',
    category: '♀️ Hormone (weiblich)',
    gender: 'female',
    units: ['ng/dL', 'nmol/L'],
    defaultUnit: 'ng/dL',
    referenceRanges: { female: { min: 15, max: 70 } },
  },
  {
    id: 'dhea_female',
    name: 'DHEA (Frau)',
    category: '♀️ Hormone (weiblich)',
    gender: 'female',
    units: ['ng/mL', 'nmol/L'],
    defaultUnit: 'ng/mL',
    cycleDependent: true,
  },
  {
    id: 'hcg',
    name: 'Beta-HCG (Schwangerschaft)',
    shortName: 'β-HCG',
    category: '♀️ Hormone (weiblich)',
    gender: 'female',
    units: ['mIU/mL', 'IU/L'],
    defaultUnit: 'mIU/mL',
    referenceRanges: { female: { min: 0, max: 5 } },
    note: 'Nicht schwanger: <5 mIU/mL; Schwangerschaft stark SSW-abhängig',
  },

  // ─── ♂️ HORMONE (MÄNNLICH) ─────────────────────────────────────
  {
    id: 'total_testosterone_male',
    name: 'Gesamttestosteron (Mann)',
    shortName: 'Testosteron',
    category: '♂️ Hormone (männlich)',
    gender: 'male',
    units: ['ng/dL', 'nmol/L'],
    defaultUnit: 'ng/dL',
    referenceRanges: { male: { min: 300, max: 1000 } },
    note: 'Morgens messen; altersabhängig (mit 60+ niedrigere Werte normal)',
  },
  {
    id: 'free_testosterone_male',
    name: 'Freies Testosteron (Mann)',
    category: '♂️ Hormone (männlich)',
    gender: 'male',
    units: ['pg/mL', 'pmol/L'],
    defaultUnit: 'pg/mL',
    referenceRanges: { male: { min: 50, max: 210 } },
    note: 'Altersabhängig; mit 40+ niedrigere Werte normal',
  },
  {
    id: 'shbg_male',
    name: 'SHBG (Mann)',
    shortName: 'SHBG',
    category: '♂️ Hormone (männlich)',
    gender: 'male',
    units: ['nmol/L'],
    defaultUnit: 'nmol/L',
    referenceRanges: { male: { min: 18, max: 54 } },
    note: 'Altersabhängig; ab 50 J. bis 80 nmol/L möglich',
  },
  {
    id: 'dht',
    name: 'DHT (Dihydrotestosteron)',
    shortName: 'DHT',
    category: '♂️ Hormone (männlich)',
    gender: 'male',
    units: ['ng/dL', 'nmol/L'],
    defaultUnit: 'ng/dL',
    referenceRanges: { male: { min: 30, max: 85 } },
  },
  {
    id: 'lh_male',
    name: 'LH (Mann)',
    shortName: 'LH',
    category: '♂️ Hormone (männlich)',
    gender: 'male',
    units: ['IU/L', 'mIU/mL'],
    defaultUnit: 'IU/L',
    referenceRanges: { male: { min: 1.7, max: 8.6 } },
  },
  {
    id: 'fsh_male',
    name: 'FSH (Mann)',
    shortName: 'FSH',
    category: '♂️ Hormone (männlich)',
    gender: 'male',
    units: ['IU/L', 'mIU/mL'],
    defaultUnit: 'IU/L',
    referenceRanges: { male: { min: 1.5, max: 12.4 } },
  },
  {
    id: 'estradiol_male',
    name: 'Östradiol (Mann)',
    shortName: 'E2',
    category: '♂️ Hormone (männlich)',
    gender: 'male',
    units: ['pg/mL', 'pmol/L'],
    defaultUnit: 'pg/mL',
    referenceRanges: { male: { min: 10, max: 40 } },
  },
  {
    id: 'psa',
    name: 'PSA (Prostata)',
    shortName: 'PSA',
    category: '♂️ Hormone (männlich)',
    gender: 'male',
    units: ['ng/mL'],
    defaultUnit: 'ng/mL',
    referenceRanges: { male: { min: 0, max: 4 } },
    note: 'Referenzwert altersabhängig',
  },

  // ─── 🦴 KNOCHEN & GELENKE ──────────────────────────────────────
  {
    id: 'pth_intact',
    name: 'Parathormon intakt (PTH)',
    shortName: 'PTH',
    category: '🦴 Knochen & Gelenke',
    gender: 'all',
    units: ['pg/mL', 'pmol/L'],
    defaultUnit: 'pg/mL',
    referenceRanges: { all: { min: 15, max: 65 } },
    note: 'Calcium und Vitamin D mitbewerten',
  },
  {
    id: 'bone_alp',
    name: 'Knochen-AP (Osteoblastenaktivität)',
    shortName: 'BAP',
    category: '🦴 Knochen & Gelenke',
    gender: 'all',
    units: ['µg/L', 'U/L'],
    defaultUnit: 'µg/L',
    referenceRanges: {
      male: { min: 6, max: 30 },
      female: { min: 5, max: 25 },
    },
    note: 'Postmenopausale Frauen können bis 35 µg/L erreichen',
  },
  {
    id: 'osteocalcin_n_mid',
    name: 'Osteocalcin (N-MID)',
    shortName: 'Osteocalcin',
    category: '🦴 Knochen & Gelenke',
    gender: 'all',
    units: ['ng/mL'],
    defaultUnit: 'ng/mL',
    referenceRanges: {
      male: { min: 14, max: 70 },
      female: { min: 11, max: 46 },
    },
    note: 'Alters-, Geschlechts- und Menopausenabhängig',
  },
  {
    id: 'crosslaps_beta',
    name: 'β-CrossLaps (Knochenabbau)',
    shortName: 'β-CTX',
    category: '🦴 Knochen & Gelenke',
    gender: 'all',
    units: ['ng/L', 'pg/mL'],
    defaultUnit: 'ng/L',
    referenceRanges: {
      male: { min: 100, max: 700 },
      female: { min: 100, max: 1000 },
    },
    note: 'Morgens nüchtern messen; postmenopausale Frauen höhere Werte',
  },

  // ─── 🧲 EISENSTOFFWECHSEL ──────────────────────────────────────
  {
    id: 'ferritin',
    name: 'Ferritin',
    category: '🧲 Eisenstoffwechsel',
    gender: 'all',
    units: ['ng/mL', 'µg/L'],
    defaultUnit: 'ng/mL',
    referenceRanges: {
      male: { min: 30, max: 400 },
      female: { min: 15, max: 150 },
    },
    note: 'Entzündung, Menstruation und Schwangerschaft beeinflussen Ferritin',
  },
  {
    id: 'iron',
    name: 'Eisen (Serum)',
    category: '🧲 Eisenstoffwechsel',
    gender: 'all',
    units: ['µg/dL', 'µmol/L'],
    defaultUnit: 'µg/dL',
    referenceRanges: {
      male: { min: 65, max: 175 },
      female: { min: 50, max: 170 },
    },
    note: 'Tageszeitabhängig; Zyklus und Supplemente beeinflussen den Wert',
  },
  {
    id: 'transferrin',
    name: 'Transferrin',
    category: '🧲 Eisenstoffwechsel',
    gender: 'all',
    units: ['g/L', 'mg/dL'],
    defaultUnit: 'g/L',
    referenceRanges: { all: { min: 2.0, max: 3.6 } },
  },
  {
    id: 'tibc',
    name: 'TIBC (Totale Eisenbindungskapazität)',
    shortName: 'TIBC',
    category: '🧲 Eisenstoffwechsel',
    gender: 'all',
    units: ['µg/dL', 'µmol/L'],
    defaultUnit: 'µg/dL',
    referenceRanges: { all: { min: 250, max: 450 } },
  },
  {
    id: 'transferrin_saturation',
    name: 'Transferrinsättigung',
    shortName: 'TfSat',
    category: '🧲 Eisenstoffwechsel',
    gender: 'all',
    units: ['%'],
    defaultUnit: '%',
    referenceRanges: { all: { min: 20, max: 45 } },
    note: 'Berechnet aus Eisen / TIBC × 100; >45 % Hinweis auf Hämochromatose',
  },
  {
    id: 'soluble_transferrin_receptor',
    name: 'Löslicher Transferrinrezeptor (sTfR)',
    shortName: 'sTfR',
    category: '🧲 Eisenstoffwechsel',
    gender: 'all',
    units: ['mg/L'],
    defaultUnit: 'mg/L',
    referenceRanges: { all: { min: 1.8, max: 4.6 } },
    note: 'Assayabhängig; erhöht bei Eisenmangel auch bei Entzündung',
  },
  {
    id: 'holo_tc_iron',
    name: 'Holo-Transcobalamin',
    shortName: 'Holo-TC',
    category: '🧲 Eisenstoffwechsel',
    gender: 'all',
    units: ['pmol/L'],
    defaultUnit: 'pmol/L',
    referenceRanges: { all: { min: 35, max: 150 } },
    note: 'Funktionell relevante Fraktion des Vitamin B12',
  },

  // ─── 🩺 SONSTIGES ──────────────────────────────────────────────
  {
    id: 'inr',
    name: 'INR (Gerinnungszeit)',
    shortName: 'INR',
    category: '🩺 Sonstiges',
    gender: 'all',
    units: [''],
    defaultUnit: '',
    referenceRanges: { all: { min: 0.85, max: 1.15 } },
  },
  {
    id: 'ptt',
    name: 'PTT / aPTT (Gerinnungszeit)',
    shortName: 'aPTT',
    category: '🩺 Sonstiges',
    gender: 'all',
    units: ['Sekunden'],
    defaultUnit: 'Sekunden',
    referenceRanges: { all: { min: 25, max: 38 } },
  },
  {
    id: 'fibrinogen',
    name: 'Fibrinogen',
    category: '🩺 Sonstiges',
    gender: 'all',
    units: ['g/L', 'mg/dL'],
    defaultUnit: 'g/L',
    referenceRanges: { all: { min: 2.0, max: 4.0 } },
  },
  {
    id: 'dimer',
    name: 'D-Dimer',
    category: '🩺 Sonstiges',
    gender: 'all',
    units: ['µg/mL', 'mg/L', 'ng/mL'],
    defaultUnit: 'µg/mL',
    referenceRanges: { all: { min: 0, max: 0.5 } },
  },
  {
    id: 'amylase',
    name: 'Amylase',
    category: '🩺 Sonstiges',
    gender: 'all',
    units: ['U/L'],
    defaultUnit: 'U/L',
    referenceRanges: { all: { min: 28, max: 100 } },
  },
  {
    id: 'lipase',
    name: 'Lipase',
    category: '🩺 Sonstiges',
    gender: 'all',
    units: ['U/L'],
    defaultUnit: 'U/L',
    referenceRanges: { all: { min: 13, max: 60 } },
  },
  {
    id: 'trypsin',
    name: 'Trypsin',
    category: '🩺 Sonstiges',
    gender: 'all',
    units: ['ng/mL'],
    defaultUnit: 'ng/mL',
    referenceRanges: { all: { min: 10, max: 57 } },
    note: 'Methodenabhängig',
  },
  {
    id: 'tryptase',
    name: 'Tryptase (Basalwert)',
    category: '🩺 Sonstiges',
    gender: 'all',
    units: ['µg/L', 'ng/mL'],
    defaultUnit: 'µg/L',
    referenceRanges: { all: { min: 0, max: 11.4 } },
    note: 'Erhöht bei Mastzellerkrankungen; akute Anstiege separat bewerten',
  },
  {
    id: 'ldh',
    name: 'LDH (Laktatdehydrogenase)',
    shortName: 'LDH',
    category: '🩺 Sonstiges',
    gender: 'all',
    units: ['U/L', 'µkat/L'],
    defaultUnit: 'U/L',
    referenceRanges: { all: { min: 122, max: 222 } },
    note: 'Hämolyseempfindlich; unspezifischer Gewebsschaden-Marker',
  },
  {
    id: 'hbdh',
    name: 'HBDH (α-Hydroxybutyrat-Dehydrogenase)',
    shortName: 'HBDH',
    category: '🩺 Sonstiges',
    gender: 'all',
    units: ['U/L'],
    defaultUnit: 'U/L',
    referenceRanges: { all: { min: 72, max: 182 } },
    note: 'Spiegelt hauptsächlich LDH-1-Isoenzym wider',
  },
  {
    id: 'ck_nac',
    name: 'Creatinkinase (CK)',
    shortName: 'CK',
    category: '🩺 Sonstiges',
    gender: 'all',
    units: ['U/L'],
    defaultUnit: 'U/L',
    referenceRanges: {
      male: { min: 39, max: 308 },
      female: { min: 26, max: 192 },
    },
    note: 'Muskelmasse und körperliche Aktivität beeinflussen die CK stark',
  },
  {
    id: 'ck_mb_mass',
    name: 'CK-MB (Herzmarker)',
    shortName: 'CK-MB',
    category: '🩺 Sonstiges',
    gender: 'all',
    units: ['ng/mL', 'µg/L'],
    defaultUnit: 'ng/mL',
    referenceRanges: { all: { min: 0, max: 5 } },
    note: 'Herzspezifische CK-Fraktion; Massenbestimmung präziser als Aktivitätsmessung',
  },
  {
    id: 'myoglobin',
    name: 'Myoglobin',
    category: '🩺 Sonstiges',
    gender: 'all',
    units: ['ng/mL'],
    defaultUnit: 'ng/mL',
    referenceRanges: {
      male: { min: 28, max: 72 },
      female: { min: 25, max: 58 },
    },
  },
  {
    id: 'ace',
    name: 'ACE (Angiotensin-Converting-Enzym)',
    shortName: 'ACE',
    category: '🩺 Sonstiges',
    gender: 'all',
    units: ['U/L'],
    defaultUnit: 'U/L',
    referenceRanges: { all: { min: 8, max: 52 } },
    note: 'Erhöht bei Sarkoidose; methodenabhängig',
  },
  {
    id: 'acid_phosphatase',
    name: 'Saure Phosphatase',
    shortName: 'SP',
    category: '🩺 Sonstiges',
    gender: 'all',
    units: ['U/L'],
    defaultUnit: 'U/L',
    referenceRanges: { all: { min: 0, max: 5.5 } },
    note: 'Heute weitgehend durch PSA ersetzt',
  },
]

// Hilfsfunktionen
export function getValuesByGender(gender: Gender): BloodValue[] {
  return BLOOD_VALUES.filter(
    (v) => v.gender === 'all' || v.gender === gender
  )
}

export function getValuesByCategory(gender: Gender): Record<string, BloodValue[]> {
  const filtered = getValuesByGender(gender)
  return filtered.reduce((acc, value) => {
    if (!acc[value.category]) acc[value.category] = []
    acc[value.category].push(value)
    return acc
  }, {} as Record<string, BloodValue[]>)
}

export function getCycleDependentValues(): BloodValue[] {
  return BLOOD_VALUES.filter((v) => v.cycleDependent)
}
